server:
  port: 8082
  servlet:
    context-path: /conciliador-api
spring:
  application:
    name: conciliador-api
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    driver-class-name: org.postgresql.Driver
    password: QqZZ^PdZvKvU!UqF
    url: jdbc:postgresql://db01.dev.boavistanet.com.br:5432/EEXTRATO_MIGRACAO_DEV
    username: bv_postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka  
